FROM openjdk
WORKDIR usr/lib
ADD ./target/springAPIGateWayService-0.0.1-SNAPSHOT.jar /usr/lib/springAPIGateWayService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","springAPIGateWayService-0.0.1-SNAPSHOT.jar"]